config:
  dirs:
    sites: ./web/_sites
    templates: ./web/templates
    static: ./web/static
    pages: ./web/pages
    data: ./web/data
  urls:
    home: https://home-page.com
    static: /static
  minify:
    js_dir: ./web/static/js
    compilation_level: ADVANCED_OPTIMIZATIONS